http:
  server: "localhost"
  port: "8081"
db:
  server: "localhost"
  port: "3306"
  database: "books"
  user: "MuleTestDB"
  password: "MuleTestDB"
account:
  balance: "600"
transfer:
  transfer_limit: "450"