#%RAML 1.0
baseUri: 
title: ems
version: v1
/employees:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              [{"name":"John","age":23},
               {"name":"Mike","age":43}]